Repository reducktion/socrates, pull requests merged in 2020-06, with the labels that each got.

#36 Docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  docs/example.png
  docs/logo.png
Labels: documentation, enhancement

#37 Implement UK!!! We're done with all countries!
  src/Config/Countries.php
  src/Core/UnitedKingdom/UnitedKingdomIdValidator.php
  tests/Feature/UnitedKingdomTest.php
  tests/Unit/ExampleUnitTest.php
Labels: enhancement

#38 PSR-12 fixes on test files and remove __toString from Citizen
  src/Models/Citizen.php
  tests/Feature/AlbaniaTest.php
  tests/Feature/BelgiumTest.php
  tests/Feature/BosniaAndHerzegovinaTest.php
  tests/Feature/BulgariaTest.php
  tests/Feature/CroatiaTest.php
  tests/Feature/CzechRepublicTest.php
  tests/Feature/DenmarkTest.php
  tests/Feature/EstoniaTest.php
  tests/Feature/FeatureTest.php
  tests/Feature/FinlandTest.php
  tests/Feature/FranceTest.php
  tests/Feature/GreeceTest.php
  tests/Feature/HungaryTest.php
  tests/Feature/IcelandTest.php
  tests/Feature/IrelandTest.php
  tests/Feature/ItalyTest.php
  tests/Feature/KosovoTest.php
  tests/Feature/LatviaTest.php
  tests/Feature/LithuaniaTest.php
  tests/Feature/LuxembourgTest.php
  tests/Feature/MoldovaTest.php
  tests/Feature/MontenegroTest.php
  tests/Feature/NetherlandsTest.php
  tests/Feature/NorthMacedoniaTest.php
  tests/Feature/NorwayTest.php
  tests/Feature/PolandTest.php
  tests/Feature/PortugalTest.php
  tests/Feature/RomaniaTest.php
  tests/Feature/SerbiaTest.php
  tests/Feature/SlovakiaTest.php
  tests/Feature/SloveniaTest.php
  tests/Feature/SpainTest.php
  tests/Feature/SwedenTest.php
  tests/Feature/SwitzerlandTest.php
  tests/Feature/TurkeyTest.php
  tests/Feature/UkraineTest.php
  tests/Feature/UnitedKingdomTest.php
  tests/SocratesTest.php
Labels: enhancement

#39 Add countries list
  README.md
  docs/COUNTRIES.md
  src/Core/BosniaAndHerzegovina/BosniaAndHerzegovinaCitizenInformationExtractor.php
  src/Core/Bulgaria/BulgariaIdValidator.php
  src/Core/Croatia/CroatiaCitizenInformationExtractor.php
  src/Core/CzechRepublic/CzechRepublicCitizenInformationExtractor.php
  src/Core/Estonia/EstoniaIdValidator.php
  src/Core/Finland/FinlandIdValidator.php
  src/Core/France/FranceIdValidator.php
  src/Core/Kosovo/KosovoCitizenInformationExtractor.php
  src/Core/Latvia/LatviaCitizenInformationExtractor.php
  src/Core/Latvia/LatviaIdValidator.php
  src/Core/Lithuania/LithuaniaIdValidator.php
  src/Core/Montenegro/MontenegroCitizenInformationExtractor.php
  src/Core/NorthMacedonia/NorthMacedoniaCitizenInformationExtractor.php
  src/Core/Serbia/SerbiaCitizenInformationExtractor.php
  src/Core/Slovakia/SlovakiaCitizenInformationExtractor.php
  src/Core/Slovenia/SloveniaCitizenInformationExtractor.php
  src/Core/Slovenia/SloveniaIdValidator.php
  tests/Feature/BulgariaTest.php
  tests/Feature/CroatiaTest.php
  tests/Feature/EstoniaTest.php
  tests/Feature/FinlandTest.php
  tests/Feature/FranceTest.php
  tests/Feature/LatviaTest.php
  tests/Feature/LithuaniaTest.php
  tests/Feature/SloveniaTest.php
Labels: documentation, enhancement

#53 Apply fixes from StyleCI
  src/Core/Albania/AlbaniaCitizenInformationExtractor.php
  src/Core/Albania/AlbaniaIdValidator.php
  src/Core/BosniaAndHerzegovina/BosniaAndHerzegovinaCitizenInformationExtractor.php
  src/Core/BosniaAndHerzegovina/BosniaAndHerzegovinaIdValidator.php
  src/Core/Bulgaria/BulgariaCitizenInformationExtractor.php
  src/Core/Bulgaria/BulgariaIdValidator.php
  src/Core/CitizenInformationExtractorFactory.php
  src/Core/Croatia/CroatiaCitizenInformationExtractor.php
  src/Core/Croatia/CroatiaIdValidator.php
  src/Core/CzechRepublic/CzechRepublicCitizenInformationExtractor.php
  src/Core/CzechRepublic/CzechRepublicIdValidator.php
  src/Core/Czechoslovakia/CzechoslovakiaCitizenInformationExtractor.php
  src/Core/Czechoslovakia/CzechoslovakiaIdValidator.php
  src/Core/Estonia/EstoniaCitizenInformationExtractor.php
  src/Core/Estonia/EstoniaIdValidator.php
  src/Core/Finland/FinlandCitizenInformationExtractor.php
  src/Core/France/FranceCitizenInformationExtractor.php
  src/Core/Greece/GreeceIdValidator.php
  src/Core/Hungary/HungaryCitizenInformationExtractor.php
  src/Core/Hungary/HungaryIdValidator.php
  src/Core/IdValidatorFactory.php
  src/Core/Ireland/IrelandIdValidator.php
  src/Core/Kosovo/KosovoCitizenInformationExtractor.php
  src/Core/Kosovo/KosovoIdValidator.php
  src/Core/Latvia/LatviaCitizenInformationExtractor.php
  src/Core/Latvia/LatviaIdValidator.php
  src/Core/Luxembourg/LuxembourgCitizenInformationExtractor.php
  src/Core/Luxembourg/LuxembourgIdValidator.php
  src/Core/Moldova/MoldovaIdValidator.php
  src/Core/Montenegro/MontenegroCitizenInformationExtractor.php
  src/Core/Montenegro/MontenegroIdValidator.php
  src/Core/Netherlands/NetherlandsIdValidator.php
  src/Core/NorthMacedonia/NorthMacedoniaCitizenInformationExtractor.php
  src/Core/NorthMacedonia/NorthMacedoniaIdValidator.php
  src/Core/Norway/NorwayCitizenInformationExtractor.php
  src/Core/Norway/NorwayIdValidator.php
  src/Core/Poland/PolandCitizenInformationExtractor.php
  src/Core/Poland/PolandIdValidator.php
  src/Core/Serbia/SerbiaCitizenInformationExtractor.php
  src/Core/Serbia/SerbiaIdValidator.php
  src/Core/Slovakia/SlovakiaCitizenInformationExtractor.php
  src/Core/Slovakia/SlovakiaIdValidator.php
  src/Core/Slovenia/SloveniaCitizenInformationExtractor.php
  src/Core/Slovenia/SloveniaIdValidator.php
  src/Core/Switzerland/SwitzerlandIdValidator.php
  src/Core/Turkey/TurkeyIdValidator.php
  src/Core/Ukraine/UkraineCitizenInformationExtractor.php
  src/Core/Ukraine/UkraineIdValidator.php
  src/Core/UnitedKingdom/UnitedKingdomIdValidator.php
  src/Core/Yugoslavia/YugoslaviaIdValidator.php
  src/Core/Yugoslavia/YugoslaviaRegions.php
  tests/TestCase.php
Labels: enhancement

#51 Fix COUNTRIES.md
  COUNTRIES.md
  README.md
Labels: documentation

#48 Validation rule
  src/Laravel/SocratesServiceProvider.php
  tests/NationalIdValidationRuleTest.php
Labels: bug

#50 Add Facade annotations
  src/Laravel/Facades/Socrates.php
Labels: enhancement

#60 Run tests on Pull Requests
  .github/workflows/php.yml
  composer.json
Labels: enhancement

#57 Correct Portugal validation algorithm
  src/Core/Portugal/PortugalIdValidator.php
  tests/Feature/PortugalTest.php
Labels: bug

#64 Fix Validation tests
  src/Core/Spain/SpainIdValidator.php
  tests/Feature/BelgiumTest.php
  tests/Feature/GreeceTest.php
  tests/Feature/IrelandTest.php
  tests/Feature/MoldovaTest.php
  tests/Feature/NetherlandsTest.php
  tests/Feature/SpainTest.php
  tests/Feature/SwitzerlandTest.php
  tests/Feature/TurkeyTest.php
  tests/Feature/UnitedKingdomTest.php
Labels: bug

#62 Add special month codes to the french ID Validator
  src/Core/France/FranceCitizenInformationExtractor.php
  tests/Feature/FranceTest.php
Labels: bug
